server:
  port: 18081
  servlet:
    context-path: /test1
spring:
  application:
    name: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true